modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "letsdocompat"
version = "${version}"
displayName = "[Let's Do Addon] Compat"
authors = "Ninjdai"
description = '''
Adds compatibility between Let's Do and a plethora of mods sos you don't have to !
'''
logoFile = "assets/cornexpansion/icon.png"

[[dependencies.letsdocompat]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.letsdocompat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.letsdocompat]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.letsdocompat]]
modId = "farm_and_charm"
mandatory = false
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"
