modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "letsdoaddoncompat"
version = "${version}"
displayName = "[Let's Do Addon] Compat"
authors = "Ninjdai"
description = '''
A Loup Garou UHC plugin
'''
#logoFile = ""

[[dependencies.letsdoaddoncompat]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.letsdoaddoncompat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.letsdoaddoncompat]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
